version: "3.9"
services:
  api:
    build: .
    container_name: travel-api-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:cached           # маунтим весь проект внутрь контейнера
      - /app/.venv              # на всякий случай скрываем локальное .venv, если появится
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload                  
# авто-перезапуск при изменении кода
